package com.portfolio.ae.stepdefs.ui;

import com.portfolio.ae.data.AccountDetails;
import com.portfolio.ae.data.ExpectedMessages;
import com.portfolio.ae.data.KnownProduct;
import com.portfolio.ae.data.ProductFixtures;
import com.portfolio.ae.data.UserDataFactory;
import com.portfolio.ae.driver.DriverManager;
import com.portfolio.ae.ui.components.HeaderComponent;
import com.portfolio.ae.ui.pages.AccountCreatedPage;
import com.portfolio.ae.ui.pages.CartPage;
import com.portfolio.ae.ui.pages.CheckoutPage;
import com.portfolio.ae.ui.pages.LoginSignupPage;
import com.portfolio.ae.ui.pages.OrderConfirmationPage;
import com.portfolio.ae.ui.pages.PaymentPage;
import com.portfolio.ae.ui.pages.ProductDetailPage;
import com.portfolio.ae.ui.pages.ProductsPage;
import com.portfolio.ae.ui.pages.SignupDetailsPage;
import com.portfolio.ae.utils.Assertions;
import io.cucumber.java.After;
import io.cucumber.java.en.And;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import org.openqa.selenium.WebDriver;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Step definitions for {@code checkout.feature}. Same as {@link RegistrationSteps}/
 * {@link LoginSteps}, it creates its own "seed" user via UI (there is no real persistent account
 * to use as a fixture) and deletes it with the same best-effort cleanup hook. The
 * {@code accountDetails} created here is needed in the address verification {@code Then}, which
 * is why this class keeps its own field instead of reusing the one from {@link LoginSteps}.
 */
public class CheckoutSteps {

    private static final Logger LOGGER = LoggerFactory.getLogger(CheckoutSteps.class);

    private AccountDetails accountDetails;
    private boolean accountPendingCleanup;

    private WebDriver driver() {
        return DriverManager.getDriver();
    }

    @Given("I am logged in with a registered account")
    public void i_am_logged_in_with_a_registered_account() {
        LoginSignupPage loginSignupPage = new LoginSignupPage(driver());
        loginSignupPage.open();
        accountDetails = UserDataFactory.randomUser();
        loginSignupPage.signup(accountDetails.name(), accountDetails.email());
        SignupDetailsPage signupDetailsPage = new SignupDetailsPage(driver());
        signupDetailsPage.fillAccountDetails(accountDetails);
        signupDetailsPage.submit();
        AccountCreatedPage accountCreatedPage = new AccountCreatedPage(driver());
        Assertions.assertContains(accountCreatedPage.getConfirmationMessage().toUpperCase(),
                ExpectedMessages.accountCreated().toUpperCase(),
                "The seed user should have been created successfully before checkout");
        accountPendingCleanup = true;
        // The site leaves the user logged in automatically after "Create Account" (confirmed in
        // LoginSteps, which does an explicit logout in order to test login); there's no need to log
        // in again, and navigating to /login with an active session redirects to home.
        accountCreatedPage.clickContinue();
        // Land on the products grid explicitly (the reliable driver.get() path) so "I add product
        // ..." doesn't depend on the post-registration home page having rendered its product cards.
        new ProductsPage(driver()).open();
    }

    @And("I go to the cart and proceed to checkout")
    public void i_go_to_the_cart_and_proceed_to_checkout() {
        CartPage cartPage = new CartPage(driver());
        cartPage.open();
        cartPage.clickProceedToCheckout();
    }

    @When("I add product {string} to the cart with quantity {string}")
    public void i_add_product_to_the_cart_with_quantity(String productId, String quantity) {
        ProductDetailPage productDetailPage = new ProductDetailPage(driver());
        productDetailPage.openProduct(productId);
        productDetailPage.setQuantity(Integer.parseInt(quantity));
        productDetailPage.addToCart();
    }

    @Then("the checkout page should show my address details")
    public void the_checkout_page_should_show_my_address_details() {
        CheckoutPage checkoutPage = new CheckoutPage(driver());
        String deliveryAddress = checkoutPage.getDeliveryAddress();
        Assertions.assertContains(deliveryAddress, accountDetails.firstName(),
                "The delivery address should show the user's name");
        Assertions.assertContains(deliveryAddress, accountDetails.address1(),
                "The delivery address should show the registered street");
        Assertions.assertContains(deliveryAddress, accountDetails.city(),
                "The delivery address should show the registered city");
    }

    @And("I place the order and pay with a dummy card")
    public void i_place_the_order_and_pay_with_a_dummy_card() {
        CheckoutPage checkoutPage = new CheckoutPage(driver());
        checkoutPage.enterOrderComment("Order generated by an automated test.");
        PaymentPage paymentPage = checkoutPage.placeOrder();
        paymentPage.enterCardDetails(accountDetails.name(), "4111111111111111", "123", "12", "2030");
        paymentPage.payAndConfirm();
    }

    @Then("I should see the order placed confirmation")
    public void i_should_see_the_order_placed_confirmation() {
        String confirmationMessage = new OrderConfirmationPage(driver()).getConfirmationMessage();
        Assertions.assertContains(confirmationMessage.toUpperCase(), ExpectedMessages.orderPlaced().toUpperCase(),
                "The order placed confirmation should be visible");
    }

    /**
     * The expected total is calculated from the fixture's unit price (PLAN.md section 7)
     * instead of hardcoding the already-multiplied amount in the feature, so it doesn't depend
     * on whoever writes the scenario doing the math by hand or on a "magic" price.
     */
    @Then("the checkout total amount should match product {string} with quantity {string}")
    public void the_checkout_total_amount_should_match_product_with_quantity(String productId, String quantity) {
        KnownProduct product = ProductFixtures.byId(productId);
        String expectedTotal = "Rs. " + (product.priceAmount() * Integer.parseInt(quantity));
        Assertions.assertEquals(new CheckoutPage(driver()).getTotalAmount(), expectedTotal,
                "The recalculated total in checkout should match unit price x quantity");
    }

    // High order => runs before Hooks.tearDownDriver (order=0), needs the driver still alive.
    @After(value = "@checkout", order = 100)
    public void cleanupLeftoverAccount() {
        if (!accountPendingCleanup || accountDetails == null) {
            return;
        }
        try {
            // Unlike RegistrationSteps/LoginSteps, this scenario never logs out during the
            // scenario, so the session stays active: no need to log in again (and if it tried,
            // /login redirects to home due to the active session, see the fix in this same component).
            new HeaderComponent(driver()).clickDeleteAccount();
        } catch (RuntimeException cleanupException) {
            LOGGER.warn("Best-effort cleanup of account '{}' failed, it may remain orphaned: {}",
                    accountDetails.email(), cleanupException.getMessage());
        } finally {
            accountPendingCleanup = false;
        }
    }
}
