package com.portfolio.ae.stepdefs.api;

import com.portfolio.ae.api.clients.AccountApiClient;
import com.portfolio.ae.api.clients.AuthApiClient;
import com.portfolio.ae.api.models.AccountRequest;
import com.portfolio.ae.api.models.ApiResponse;
import com.portfolio.ae.api.models.UserAccount;
import com.portfolio.ae.api.models.UserDetailResponse;
import com.portfolio.ae.utils.Assertions;
import com.portfolio.ae.utils.FakerUtil;
import io.cucumber.java.After;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Step definitions for {@code account_lifecycle_api.feature}: full chain create -> verify ->
 * update -> getDetail -> delete (PLAN.md section 4), all with data generated by
 * {@link FakerUtil}/{@link AccountRequest}.
 */
public class AccountLifecycleApiSteps {

    private static final Logger LOGGER = LoggerFactory.getLogger(AccountLifecycleApiSteps.class);
    private static final String PASSWORD = "Passw0rd!123";

    private final AccountApiClient accountApiClient = new AccountApiClient();
    private final AuthApiClient authApiClient = new AuthApiClient();

    private String email;
    private AccountRequest currentAccount;
    private boolean accountPendingCleanup;

    private ApiResponse lastApiResponse;
    private UserDetailResponse lastUserDetailResponse;

    @When("I create a new account via the API")
    public void i_create_a_new_account_via_the_api() {
        email = FakerUtil.uniqueEmail();
        currentAccount = AccountRequest.anAccount()
                .withName("Lifecycle User")
                .withEmail(email)
                .withPassword(PASSWORD)
                .withFirstName("Lifecycle")
                .withLastName("User")
                .withAddress1("123 Lifecycle St")
                .withCity("Lifecycle City")
                .withState("CA")
                .withZipcode("90001")
                .withMobileNumber("5551234567");

        lastApiResponse = accountApiClient.createAccount(currentAccount);
        accountPendingCleanup = true;
    }

    @Then("the account creation response code should be {int}")
    public void the_account_creation_response_code_should_be(int expectedResponseCode) {
        Assertions.assertEquals(lastApiResponse.getResponseCode(), expectedResponseCode,
                "The createAccount responseCode does not match the expected value");
    }

    @When("I verify login for the account I just created")
    public void i_verify_login_for_the_account_i_just_created() {
        lastApiResponse = authApiClient.verifyLogin(email, PASSWORD);
    }

    @Then("the account login verification response code should be {int}")
    public void the_account_login_verification_response_code_should_be(int expectedResponseCode) {
        Assertions.assertEquals(lastApiResponse.getResponseCode(), expectedResponseCode,
                "The verifyLogin responseCode does not match the expected value");
    }

    @When("I fetch the user details by email")
    public void i_fetch_the_user_details_by_email() {
        lastUserDetailResponse = accountApiClient.getUserDetailByEmail(email);
    }

    @Then("the user details should match the account I created")
    public void the_user_details_should_match_the_account_i_created() {
        Assertions.assertEquals(lastUserDetailResponse.getResponseCode(), 200,
                "getUserDetailByEmail should return 200 after creating the account");
        UserAccount user = lastUserDetailResponse.getUser();
        Assertions.assertEquals(user.getFirstName(), "Lifecycle",
                "The firstName should match that of the created account");
        Assertions.assertEquals(user.getCity(), "Lifecycle City",
                "The city should match that of the created account");
    }

    @When("I update the account with new details")
    public void i_update_the_account_with_new_details() {
        currentAccount = AccountRequest.anAccount()
                .withName("Lifecycle User Updated")
                .withEmail(email)
                .withPassword(PASSWORD)
                .withFirstName("LifecycleUpdated")
                .withLastName("UserUpdated")
                .withAddress1("456 Updated Ave")
                .withCity("Updated City")
                .withState("NY")
                .withZipcode("10001")
                .withMobileNumber("5559876543");

        lastApiResponse = accountApiClient.updateAccount(currentAccount);
    }

    @Then("the account update response code should be {int}")
    public void the_account_update_response_code_should_be(int expectedResponseCode) {
        Assertions.assertEquals(lastApiResponse.getResponseCode(), expectedResponseCode,
                "The updateAccount responseCode does not match the expected value");
    }

    @Then("the user details should match the updated account")
    public void the_user_details_should_match_the_updated_account() {
        UserAccount user = lastUserDetailResponse.getUser();
        Assertions.assertEquals(user.getFirstName(), "LifecycleUpdated",
                "The firstName should reflect the update");
        Assertions.assertEquals(user.getCity(), "Updated City",
                "The city should reflect the update");
    }

    @When("I delete the account")
    public void i_delete_the_account() {
        lastApiResponse = accountApiClient.deleteAccount(email, PASSWORD);
        accountPendingCleanup = false;
    }

    @Then("the account deletion response code should be {int}")
    public void the_account_deletion_response_code_should_be(int expectedResponseCode) {
        Assertions.assertEquals(lastApiResponse.getResponseCode(), expectedResponseCode,
                "The deleteAccount responseCode does not match the expected value");
    }

    @Then("the user details response code should be {int}")
    public void the_user_details_response_code_should_be(int expectedResponseCode) {
        Assertions.assertEquals(lastUserDetailResponse.getResponseCode(), expectedResponseCode,
                "The getUserDetailByEmail responseCode does not match the expected value");
    }

    // High order: does not depend on the UI driver, just needs to run after the scenario ends.
    @After(value = "@account and @api", order = 100)
    public void cleanupLeftoverAccount() {
        if (!accountPendingCleanup) {
            return;
        }
        try {
            accountApiClient.deleteAccount(email, PASSWORD);
        } catch (RuntimeException cleanupException) {
            LOGGER.warn("Best-effort cleanup of account '{}' failed, it may remain orphaned: {}",
                    email, cleanupException.getMessage());
        } finally {
            accountPendingCleanup = false;
        }
    }
}
